---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Download the venv
  get_url:
    url: "{{ item.src }}"
    dest: "/var/lib/lxc/{{ lxc_cache_name }}/rootfs/{{ item.cache }}/{{ item.src | basename }}"
    checksum: "{{ item.checksum }}"
  register: _venv_download
  delegate_to: "{{ lxc_cache_physical_host | default(omit) }}"

- name: Remove venv destination directory (if venv checksum changed)
  file:
    path: "/var/lib/lxc/{{ lxc_cache_name }}/rootfs{{ item.dest }}"
    state: absent
  when: _venv_download | changed
  delegate_to: "{{ lxc_cache_physical_host | default(omit) }}"

- name: Create venv destination directory
  file:
    path: "/var/lib/lxc/{{ lxc_cache_name }}/rootfs{{ item.dest }}"
    state: directory
  register: _venv_create
  delegate_to: "{{ lxc_cache_physical_host | default(omit) }}"

- name: Unarchive the venv
  unarchive:
    src: "/var/lib/lxc/{{ lxc_cache_name }}/rootfs/{{ item.cache }}/{{ item.src | basename }}"
    dest: "/var/lib/lxc/{{ lxc_cache_name }}/rootfs{{ item.dest }}"
    remote_src: yes
  when: _venv_download | changed or _venv_create | changed
  delegate_to: "{{ lxc_cache_physical_host | default(omit) }}"

- name: Update virtualenv python executable and paths
  command: "chroot /var/lib/lxc/{{ lxc_cache_name }}/rootfs virtualenv-tools --reinitialize --update-path=auto {{ item.dest }}"
  when: _venv_download | changed or _venv_create | changed
  delegate_to: "{{ lxc_cache_physical_host | default(omit) }}"
